### ISSUE TITLE
Deploy the statsboard at ODC

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#1]
EMB wants to have the statistics board in ODC as soon as possible (which does not mean now), at least a public version with EIDA, node and network levels.

I feel that there is some more work to be done first.

- in the statsboard itself (@vpet98 )
- at ODC side (@jbienkowski)

Let's list the tasks and issues here.

**Comment by jschaeff** [comment]
It would be good to solve issue https://github.com/EIDA/eida-statistics/issues/45

**Comment by jbienkowski** [comment]
I have just added to our internal ticketing system, it will be included in out planning.

**Comment by vpet98** [comment]
Hello,

I am commenting here following what was discussed in the online meeting on the 5th of July and is probably to be seen when you are back from vacation time.

A first version of the statistics board is ready to go into production. I think that cloning the project, getting into the statsboard folder and executing the command `npm run build` produces a build folder with static files that will be enough for deploying the app. The contents of the folder will be similar to the [https://github.com/EIDA/statsboard/tree/gh-pages](https://github.com/EIDA/statsboard/tree/gh-pages) branch of the current project if you want to have a look first. If you'd like, I can execute the command locally and provide directly the build folder to you. If this is not enough to deploy, let's discuss here what else is needed.

Have a nice vacation time!

**Comment by Jollyfant** [comment]
Hi all! We've added an iFrame that points to the GitHub pages of this repository: https://orfeus-eu.org/data/eida/stats/. This way we should automatically get any updates to this package propagated.
