### ISSUE TITLE
Small bug in the date format

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#19]
![image](https://github.com/EIDA/statsboard/assets/1147747/24df784b-0ffd-420e-8cf1-30cc6777daaf)

I guess `MMMM` should be replaced by `MM`

**Comment by vpet98** [comment]
This is the default of the library used and makes months appear as words when a month is chosen. With ```MM``` months will appear as numbers (e.g. 01 instead of January).

Fixed
