### ISSUE TITLE
When asking for non complete years, do not render yearly graphs.

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#21]
For example if I ask for Jan 2023 - Jan 2023, the stats for that year appear as the one for the month

**Comment by vpet98** [comment]
When asking for non complete years the yearly graph shows information for the timeframe of the year asked.

If stats are asked from Jan 2023 with no end time then yearly results will be for 2023 until current month. If asked for Jan 2023 until May 2023 then yearly results will be for these 5 months. Of course, these plots will be equivalent with the pies in these cases.

But, If stats are asked for last half of 2022 and first half of 2023 then yearly results will have two columns, one for each half year. For this one, the other plots cannot provide an equivalent in one user request.

So, what we would like to do in each case?

**Comment by jschaeff** [comment]
@helle-pedersen do you have any comment ?

**Comment by jschaeff** [comment]
Proposition:

- when there is only one point, just render the values instead of the graphics
- when the graphic concern incomplete years (or month), add at least a comment that warns the user that the some points represent only a part of the time bucket.
