### ISSUE TITLE
Frequent 500 errors

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#23]
For the request EIDA in Jan 2023, I have Service is temporarily unavailable. Please try again. 

This happened several times. After ‘number of unique users per year’.

I then did if for RESIF, it worked. Going back to EIDA it worked.  The issue of Service temporarily unavailable seems to happen quite often, is there a way to analyse this?

**Comment by vpet98** [comment]
This seems to happen the first time the service is used after long time of no use. Refreshing the page after failed requests should make it work. Not sure why this happens.

If it happens continuously after refreshing, then must be problem of the statistics webservice and not of the board.

**Comment by jschaeff** [comment]
Could you integrate sentry in the webservice code ?

I sent you an invite to the platform. Here is the startup guide: https://osug.sentry.io/projects/eidastats/getting-started/

**Comment by vpet98** [comment]
I think I did it. Main branch. Needs to be tested to be sure it's ok.

**Comment by vpet98** [comment]
Converstion continued here: https://github.com/EIDA/eida-statistics/issues/48
