### ISSUE TITLE
N/A in graphs and partial graphing

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#25]
This is the results of the request by networks, on node RESIF, without selecting any network:

![image](https://github.com/EIDA/statsboard/assets/1147747/793181de-ec94-4467-a783-28c803541159)

The graph only starts in june.

Note that if i export as image using the camera button, I can see everything:
![newplot(2)](https://github.com/EIDA/statsboard/assets/1147747/d0fff772-1f9d-4ef2-a117-81aa1d28b93b)

And "unselecting" the "N/A" curve, it shows everything:

![newplot(3)](https://github.com/EIDA/statsboard/assets/1147747/c4b4ccda-15dc-4105-9669-85f6772c4662)

Looks like a graphical library problem ?

**Comment by vpet98** [comment]
This is weird. I can see everything when I try it with the N/A and without exporting the plot.

![Screenshot from 2023-11-21 15-43-01](https://github.com/EIDA/statsboard/assets/57916087/1b1491de-0aab-4a97-8eea-875dcfeb352e)

Could it be a browser problem?

**Comment by jschaeff** [comment]
I use firefox 119, so I expect it to work alright.

Issue reproduces on a windows machine, I don't know which browser. Wating for Helle to join the group and follow the issue.

**Comment by vpet98** [comment]
Just tested it. In my Chrome browser there is no problem. In my Firefox browser I reproduce your problem.

I'll look at it but not sure if this can be solved from my side.

**Comment by jschaeff** [comment]
If the problem happens when there are missing values, maybe we could set the webservice to put "0" in place of missing values.

But I saw other graphs with missing values that work alright ...

**Comment by vpet98** [comment]
When more than 20 months are requested, plotly automatically removes the dots from the lines.

The problem appears when more than 20 months are requested and one of the networks has less than 20 months available.

Don't know why this causes a problem in some browsers, but what you proposed could work. I'll try it.

**Comment by vpet98** [comment]
Problem fixed and deployed. I forced having dots in lines always.

**Comment by jschaeff** [comment]
@helle-pedersen this issue is fixed :)

![image](https://github.com/EIDA/statsboard/assets/1147747/0133b4bf-0b62-49eb-a445-180df26c637b)
