### ISSUE TITLE
Asking for several network is not supported

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#27]
Either we remove the possibility to build such a request by making network field unique, or we fix it.

Any hints on what would be required to fix it?

Example: 

![image](https://github.com/EIDA/statsboard/assets/1147747/62fe3087-464f-491b-b686-c524497421df)

**Comment by vpet98** [comment]
It is deliberately designed this way for the case a node operator with their token uses the board.

The board itself cannot tell who the user is even when having the token.

**Comment by jschaeff** [comment]
Yes I remember now. Maybe a clearer error message would be helpful ?
Something like: 
"Requesting several network requires node operator privilege. Please reach the support if you need more privileges"

**Comment by vpet98** [comment]
In the case we are talking about, the **webservice** assumes that only one network is specified becasue of the non-operator token. So it takes, for example, `&network=NET1,NET2` and responds that there is no network that matches this name. Then the board directly prints this error.

One way to override this is to assume that when networks are chosen from autocompletion list they cannot be misspelled and thus getting this error from the webservice leaves no other case than the one we are talking about. However, still if the user chooses to type some network(s) in the field without selecting from the list, the non-matching network name error should appear.

It's a bit dirty, but could do the work.

**Comment by jschaeff** [comment]
A variant would be to do some logic in the web page.
Assume there is no coma in a network name.
If the network field contains a coma (or by forcing values from autocomplete, when there is more than one network), statsboard could add a warning sign next to the field or in a banner:

"Selecting multiple network requires node operator privileges. Make sure your EIDA account is set up accordingly" ?

Then, the user can issue the request, will get the initial error message. But at least we warned her :)

**Comment by vpet98** [comment]
Warning added
