### ISSUE TITLE
Help the user to enter several stations

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#28]
The way to enter several stations is not intuitive.

We should either build autocompletion list or add a tooltip to say how to list stations.

The correct way for now is a coma separated list of names.

![image-2](https://github.com/EIDA/statsboard/assets/1147747/9e9d8c06-2ddf-4972-adaf-687385c16eda)

**Comment by vpet98** [comment]
The autocompletion for stations was ruled out because no stations information or table exists in statistics database and also would probably lead to problematically huge autocompletion lists.

I can add a tooltip.

**Comment by vpet98** [comment]
Added
