### ISSUE TITLE
Create direct links for a type of parameters

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#29]
I miss the ability to share via an URL the exact request I made.

For instance after a request with fine parameters, I would like to share the result to someone else, by sending her a link.
Would it be possible to add a "share" button ? Like the snapshot feature un Grafana.

**Comment by vpet98** [comment]
This board is a single page interacive site. No url with the user's request parameters is ever generated. I don't think this is possible in the current version.

**Comment by jschaeff** [comment]
This feature would mean to build a whole applicatin I guess.

As a workaround, it could be nice to get the URL requests made to the API as a copy button. It would enable researchers to crunch the numbers more easily.

**Comment by jschaeff** [comment]
dump it.
