### ISSUE TITLE
Add information for the user about unique users indicator

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#30]
Could you add a tooltip for the users to show an important warning about the way the unique users are counted ?

Could you do this by the end of the week please ?

For instance here,
![image](https://github.com/EIDA/statsboard/assets/1147747/2d0db8b3-5810-45df-932b-10e15fe9dc25)

but also on each graph representing unique users.

The text can be:

>
> Unique users are estimated based on anonymised distinct IP addresses of the clients issuing requests.
>

**Comment by vpet98** [comment]
Done!
