### ISSUE TITLE
Add a GDPR banner on the web interface

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#31]
As the API collects usage metrics.

Find a correct formulation for this.

**Comment by vpet98** [comment]
Could use some more info about this. 

For example, a link in the description page to some gdpr page would do?

Or you mean something like a cookie popup?

But statistics are collected from the use of other services and not from the statistics service, right?

**Comment by jschaeff** [comment]
All request to our services are logged in the following manner:
1. haproxy logs the request
2. this log is shipped to an opensearch database, not anonymised as for the IP address
Those logs are important in order to operate the service and identify problems.

There is also the token authentified part of the API. We should state something about what is kept in the logs from those requests. I think we do not keep any trace of it as for now, but it also should be stated I guess.

There are 2 places where we should inform user of personnal data usage by the service operator, I guess:
1. the webservice documentation
2. the statistics UI.

I think it does not require consent because we actually need the information to operate the system but the user should be informed that the IP addresses are kept in our systems for 6 months, then deleted.

Well, the cleanest way to address this might not be this. I'm not really sure.

**Comment by jschaeff** [comment]
Maybe just mention that the API behind is hosted at Résif and user have to be aware of the terms of services: http://ws.resif.fr/terms_of_services/

**Comment by vpet98** [comment]
Done
