### ISSUE TITLE
Autocompletion in the form fields

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#4]
- should it be possible to select one or more nodes  when going at node level ?
- month selection auto completion
- networks auto completion at network level

**Comment by vpet98** [comment]
It could be possible to select nodes at node level through a field. Currently, it is possible to select nodes in the interactive plots. Do we really need the field as well?

How could month autocompletion work? By pressing 3 or clicking "Mar", March is selected. How can it be simpler than this?

Networks autocompletion can be imlpemented by having one more call to the webservice in the /networks endpoint.

**Comment by jschaeff** [comment]
- selecting nodes at node level:  to me it would be useful, because if only interested in one node, this would speed up the rendering a lot
- date autocompletion, here are some options that seem convenient to me:
  - split the date in year and month and put a list of values
  - pop up a calendar view (but would not allow to select a day, only month or year)
- network autocompletion is a must :) (and partly the reason why I asked for the /networks endpoint)
