### ISSUE TITLE
Title for number of unique users

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#8]
At node level :

"Users per nodes"
"Total of unique users"

At network level:

"Users per network"
"Total of unique users"

Report this to other plots

**Comment by vpet98** [comment]
Done. Will take effect next time I deploy. I have kept the word "Total" for all cases in the pie charts, because it refers to the _total numbers accross the specified time period_ in contrast with the bar plots, which show numbers per month/year.
