### ISSUE TITLE
Merge small values in pie charts

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#9]
All values less than 3% for instance could be summed up in the same slice.

![image](https://github.com/EIDA/statsboard/assets/1147747/250f9f94-4feb-4b90-94c0-a9e3a5ce4eb2)

**Comment by vpet98** [comment]
Any idea for the label of the slice since 'Other' is kept for the restricted networks? Maybe use 'Restricted' for the restricted and 'Others' for the case here?

**Comment by jschaeff** [comment]
The label could be explicit (`less than 3 %`) ?

**Comment by vpet98** [comment]
Done. Change will take effect in next deployment.
